apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: auth-config
    files:
      - ./config/auth.php