---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testrail
  name: testrail
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  selector:
    app: testrail
